name: Docker Image CI

on: 
  push:
    branches:
    - master

jobs:

  deploy:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1

    - name: Google Cloud Auth
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: Google Cloud deploy
      uses: actions/gcloud/cli@master
      with:
        args: components install beta --quiet && gcloud config set project mashhoodr && gcloud builds submit --tag gcr.io/mashhoodr/helloworld && gcloud beta run deploy --image gcr.io/mashhoodr/helloworld --platform managed
          
